// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InstantSearchController from "./instant_search_controller"
application.register("instant-search", InstantSearchController)

import StepGuideController from "./step_guide_controller"
application.register("step-guide", StepGuideController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TransitionsController from "./transitions_controller"
application.register("transitions", TransitionsController)
